### ISSUE TITLE
Changement sxhkdrc_bspwm

### ISSUE THREAD

**Issue by Breizil29** [archusXIV/wm_config#3]
Salut @archusXIV, j'utilise un clavier QWERTY 75% donc j'ai changé le fichier :
sxhkdrc_bspwm
Remplacé : 
`# focus or send (focused node) to the given desktop (using numpad).
super + {_,alt + }{KP_End,KP_Down,KP_Next,KP_Left,KP_Begin,KP_Right,KP_Home,KP_Up,KP_Prior,KP_Insert}
    bspc {desktop -f,node -d} '^{1-9,10}'`
Par :
`# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'`
Cela fonctionne sauf qu'au démarrage je suis obligé de :
`bspc wm -r`
pour que cela fonctionne à nouveau.

**Comment by archusXIV** [comment]
Comment lances-tu sxhkd, avec un script ou dans .config/bspwm/bspwmrc:
pgrep -x sxhkd || sxhkd -m -1 &
Si c'est le script sxhkd-start que tu utilises fais le démarrer à la toute fin de bspwmrc....
Tu as choisis le clavier français lors de l'installation, peut-etre dois-tu changer quelque chose dans /etc/locale.conf....
Dans un terminal tape: localectl

**Comment by Breizil29** [comment]
J´utilise ton script i3/bspwm install
`    # External scripts & settings
    _Check launch_polybar && launch_polybar &
    _Check sxhkd-start && sxhkd-start &
    _Check pcloud-start && pcloud-start &
    _Check bspwm_backnforth && bspwm_backnforth
    _Check bspwm_external_rules && \
        bspc config external_rules_command \
            "$(which bspwm_external_rules)"`
Je t´affiche mon ¨bspwmrc" car je me demande si pcloud ne fout pas la merde.
Et le clavier je maîtrise, mon /etc/vconsole :
`/etc/vconsole.conf
KEYMAP=us
FONT=lat2-16
XKBLAYOUT=us
XKBMODEL=pc105
XKBVARIANT=intl`

**Comment by archusXIV** [comment]
Puisque ton "keyboard layout" est "us" alors je pense que tu peux te passer du fichirer Xmodmap ou alors lancer la command:
`xmodmap -pke > ~/.Xmodmap && xmodmap ~/.Xmodmap`

https://wiki.archlinux.org/title/Xmodmap#Custom_table

**Comment by Breizil29** [comment]
Nickel, ça fonctionne.
Merci
