### ISSUE TITLE
Modify .zshrc to drop into fish

### ISSUE THREAD

**Issue by Breizil29** [archusXIV/wm_config#5]
Hello @archusXIV i want to change set fish as interactive shell only and
keep the default shell as Zsh.

The command given by ArchWiki is for bash  :

```
> if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]
> then
> shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
> exec fish $LOGIN_OPTION
> fi
```

I would like the same for .zshrc.
PLEASE

**Comment by archusXIV** [comment]
From my point of view I won't change anything to ~/.xinitrc and keep zsh as my default (login) shell but only get into fish when I launch a terminal.
For example in the sxhkdrc:
super + Return
    my_terminal_name -e fish

**Comment by Breizil29** [comment]
Yes thank you, that's what I wanted.
